services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    env_file: .env
    volumes:
      - ./n8n_data:/home/node/.n8n

  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   environment:
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  #   command: tunnel run